//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatroom
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string PASSWRD { get; set; }
        public string USERNAME { get; set; }
        public string REGDATE { get; set; }
        public string REGTIME { get; set; }
    }
}
